source 'https://rubygems.org'

ruby '3.2.2'

gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.2'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'mocha', '~> 2.1', require: false
end
